### ISSUE TITLE
Add License to Library

### ISSUE THREAD

**Issue by FuadBalashov** [jasonmendes/tslint-no-focused-test#3]
Hello, thank you for sharing this lint rule! I was looking for exactly this rule for TSLint. Could you add a license to this library so it is clear how it can be used?

Thanks!

**Comment by jasonmendes** [comment]
@FuadBalashov Hey, thanks for asking about this! Is there a license that would work best for you? I'm not well versed on the different types. I'd probably just use MIT as a good default, though.

**Comment by parkerholladay** [comment]
MIT would be fine.

**Comment by jasonmendes** [comment]
@parkerholladay Great ^_^ Let me know if this looks good to you -- https://github.com/jasonmendes/tslint-no-focused-test/pull/4

**Comment by jasonmendes** [comment]
Resolved with #4 Thanks for bringing this up @FuadBalashov
